// Code generated by ent, DO NOT EDIT.

package aspectratio

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aspectratio type in the database.
	Label = "aspect_ratio"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRatio holds the string denoting the ratio field in the database.
	FieldRatio = "ratio"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// Table holds the table name of the aspectratio in the database.
	Table = "aspect_ratios"
)

// Columns holds all SQL columns for aspectratio fields.
var Columns = []string{
	FieldID,
	FieldRatio,
	FieldWidth,
	FieldHeight,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AspectRatio queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRatio orders the results by the ratio field.
func ByRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatio, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}
