// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArtworksColumns holds the columns for the "artworks" table.
	ArtworksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_ai", Type: field.TypeBool, Default: false},
		{Name: "comment_generated_artwork", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "media_artworks", Type: field.TypeInt},
		{Name: "user_artworks", Type: field.TypeInt},
	}
	// ArtworksTable holds the schema information for the "artworks" table.
	ArtworksTable = &schema.Table{
		Name:       "artworks",
		Columns:    ArtworksColumns,
		PrimaryKey: []*schema.Column{ArtworksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artworks_comments_generated_artwork",
				Columns:    []*schema.Column{ArtworksColumns[7]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "artworks_media_artworks",
				Columns:    []*schema.Column{ArtworksColumns[8]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "artworks_users_artworks",
				Columns:    []*schema.Column{ArtworksColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "artwork_title",
				Unique:  false,
				Columns: []*schema.Column{ArtworksColumns[4]},
			},
			{
				Name:    "artwork_description",
				Unique:  false,
				Columns: []*schema.Column{ArtworksColumns[5]},
			},
		},
	}
	// AspectRatiosColumns holds the columns for the "aspect_ratios" table.
	AspectRatiosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ratio", Type: field.TypeString},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
	}
	// AspectRatiosTable holds the schema information for the "aspect_ratios" table.
	AspectRatiosTable = &schema.Table{
		Name:       "aspect_ratios",
		Columns:    AspectRatiosColumns,
		PrimaryKey: []*schema.Column{AspectRatiosColumns[0]},
	}
	// BaseConfigsColumns holds the columns for the "base_configs" table.
	BaseConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Size: 2147483647},
	}
	// BaseConfigsTable holds the schema information for the "base_configs" table.
	BaseConfigsTable = &schema.Table{
		Name:       "base_configs",
		Columns:    BaseConfigsColumns,
		PrimaryKey: []*schema.Column{BaseConfigsColumns[0]},
	}
	// ComfyUINodesColumns holds the columns for the "comfy_ui_nodes" table.
	ComfyUINodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// ComfyUINodesTable holds the schema information for the "comfy_ui_nodes" table.
	ComfyUINodesTable = &schema.Table{
		Name:       "comfy_ui_nodes",
		Columns:    ComfyUINodesColumns,
		PrimaryKey: []*schema.Column{ComfyUINodesColumns[0]},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "depth", Type: field.TypeInt, Default: 0},
		{Name: "comment_children", Type: field.TypeInt, Nullable: true},
		{Name: "user_comments", Type: field.TypeInt},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_comments_children",
				Columns:    []*schema.Column{CommentsColumns[6]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "comments_users_comments",
				Columns:    []*schema.Column{CommentsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "comment_depth_comment_children",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[5], CommentsColumns[6]},
			},
		},
	}
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "url", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
		{Name: "primary_corlor", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "media_hash",
				Unique:  true,
				Columns: []*schema.Column{MediaColumns[9]},
			},
			{
				Name:    "media_key",
				Unique:  true,
				Columns: []*schema.Column{MediaColumns[4]},
			},
		},
	}
	// StylesColumns holds the columns for the "styles" table.
	StylesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
	}
	// StylesTable holds the schema information for the "styles" table.
	StylesTable = &schema.Table{
		Name:       "styles",
		Columns:    StylesColumns,
		PrimaryKey: []*schema.Column{StylesColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user", "ai"}},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tag_name_type",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[3], TagsColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "bio", Type: field.TypeString, Nullable: true},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"github", "google", "microsoft"}},
		{Name: "provider_account_id", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "admin"}, Default: "user"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "banned"}, Default: "active"},
		{Name: "is_favorites_public", Type: field.TypeBool, Default: true},
		{Name: "is_likes_public", Type: field.TypeBool, Default: true},
		{Name: "recent_tags", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_provider_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[7], UsersColumns[8]},
			},
		},
	}
	// WorkflowsColumns holds the columns for the "workflows" table.
	WorkflowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"image_to_image", "text_to_image", "comment_to_image"}},
		{Name: "json", Type: field.TypeString},
		{Name: "image_result_node", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "style_workflows", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// WorkflowsTable holds the schema information for the "workflows" table.
	WorkflowsTable = &schema.Table{
		Name:       "workflows",
		Columns:    WorkflowsColumns,
		PrimaryKey: []*schema.Column{WorkflowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "workflows_styles_workflows",
				Columns:    []*schema.Column{WorkflowsColumns[9]},
				RefColumns: []*schema.Column{StylesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ArtworkCommentsColumns holds the columns for the "artwork_comments" table.
	ArtworkCommentsColumns = []*schema.Column{
		{Name: "artwork_id", Type: field.TypeInt},
		{Name: "comment_id", Type: field.TypeInt},
	}
	// ArtworkCommentsTable holds the schema information for the "artwork_comments" table.
	ArtworkCommentsTable = &schema.Table{
		Name:       "artwork_comments",
		Columns:    ArtworkCommentsColumns,
		PrimaryKey: []*schema.Column{ArtworkCommentsColumns[0], ArtworkCommentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artwork_comments_artwork_id",
				Columns:    []*schema.Column{ArtworkCommentsColumns[0]},
				RefColumns: []*schema.Column{ArtworksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "artwork_comments_comment_id",
				Columns:    []*schema.Column{ArtworkCommentsColumns[1]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// CommentLikesColumns holds the columns for the "comment_likes" table.
	CommentLikesColumns = []*schema.Column{
		{Name: "comment_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CommentLikesTable holds the schema information for the "comment_likes" table.
	CommentLikesTable = &schema.Table{
		Name:       "comment_likes",
		Columns:    CommentLikesColumns,
		PrimaryKey: []*schema.Column{CommentLikesColumns[0], CommentLikesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comment_likes_comment_id",
				Columns:    []*schema.Column{CommentLikesColumns[0]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "comment_likes_user_id",
				Columns:    []*schema.Column{CommentLikesColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TagArtworksColumns holds the columns for the "tag_artworks" table.
	TagArtworksColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "artwork_id", Type: field.TypeInt},
	}
	// TagArtworksTable holds the schema information for the "tag_artworks" table.
	TagArtworksTable = &schema.Table{
		Name:       "tag_artworks",
		Columns:    TagArtworksColumns,
		PrimaryKey: []*schema.Column{TagArtworksColumns[0], TagArtworksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_artworks_tag_id",
				Columns:    []*schema.Column{TagArtworksColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_artworks_artwork_id",
				Columns:    []*schema.Column{TagArtworksColumns[1]},
				RefColumns: []*schema.Column{ArtworksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserLikedArtworksColumns holds the columns for the "user_liked_artworks" table.
	UserLikedArtworksColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "artwork_id", Type: field.TypeInt},
	}
	// UserLikedArtworksTable holds the schema information for the "user_liked_artworks" table.
	UserLikedArtworksTable = &schema.Table{
		Name:       "user_liked_artworks",
		Columns:    UserLikedArtworksColumns,
		PrimaryKey: []*schema.Column{UserLikedArtworksColumns[0], UserLikedArtworksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_liked_artworks_user_id",
				Columns:    []*schema.Column{UserLikedArtworksColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_liked_artworks_artwork_id",
				Columns:    []*schema.Column{UserLikedArtworksColumns[1]},
				RefColumns: []*schema.Column{ArtworksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserFollowingColumns holds the columns for the "user_following" table.
	UserFollowingColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "follower_id", Type: field.TypeInt},
	}
	// UserFollowingTable holds the schema information for the "user_following" table.
	UserFollowingTable = &schema.Table{
		Name:       "user_following",
		Columns:    UserFollowingColumns,
		PrimaryKey: []*schema.Column{UserFollowingColumns[0], UserFollowingColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_following_user_id",
				Columns:    []*schema.Column{UserFollowingColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_following_follower_id",
				Columns:    []*schema.Column{UserFollowingColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArtworksTable,
		AspectRatiosTable,
		BaseConfigsTable,
		ComfyUINodesTable,
		CommentsTable,
		MediaTable,
		StylesTable,
		TagsTable,
		UsersTable,
		WorkflowsTable,
		ArtworkCommentsTable,
		CommentLikesTable,
		TagArtworksTable,
		UserLikedArtworksTable,
		UserFollowingTable,
	}
)

func init() {
	ArtworksTable.ForeignKeys[0].RefTable = CommentsTable
	ArtworksTable.ForeignKeys[1].RefTable = MediaTable
	ArtworksTable.ForeignKeys[2].RefTable = UsersTable
	CommentsTable.ForeignKeys[0].RefTable = CommentsTable
	CommentsTable.ForeignKeys[1].RefTable = UsersTable
	WorkflowsTable.ForeignKeys[0].RefTable = StylesTable
	ArtworkCommentsTable.ForeignKeys[0].RefTable = ArtworksTable
	ArtworkCommentsTable.ForeignKeys[1].RefTable = CommentsTable
	CommentLikesTable.ForeignKeys[0].RefTable = CommentsTable
	CommentLikesTable.ForeignKeys[1].RefTable = UsersTable
	TagArtworksTable.ForeignKeys[0].RefTable = TagsTable
	TagArtworksTable.ForeignKeys[1].RefTable = ArtworksTable
	UserLikedArtworksTable.ForeignKeys[0].RefTable = UsersTable
	UserLikedArtworksTable.ForeignKeys[1].RefTable = ArtworksTable
	UserFollowingTable.ForeignKeys[0].RefTable = UsersTable
	UserFollowingTable.ForeignKeys[1].RefTable = UsersTable
}
