// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/artwork"
	"github.com/MiaoMint/animaerd/ent/comment"
	"github.com/MiaoMint/animaerd/ent/media"
	"github.com/MiaoMint/animaerd/ent/tag"
	"github.com/MiaoMint/animaerd/ent/user"
)

// ArtworkCreate is the builder for creating a Artwork entity.
type ArtworkCreate struct {
	config
	mutation *ArtworkMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ac *ArtworkCreate) SetCreateTime(t time.Time) *ArtworkCreate {
	ac.mutation.SetCreateTime(t)
	return ac
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableCreateTime(t *time.Time) *ArtworkCreate {
	if t != nil {
		ac.SetCreateTime(*t)
	}
	return ac
}

// SetUpdateTime sets the "update_time" field.
func (ac *ArtworkCreate) SetUpdateTime(t time.Time) *ArtworkCreate {
	ac.mutation.SetUpdateTime(t)
	return ac
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableUpdateTime(t *time.Time) *ArtworkCreate {
	if t != nil {
		ac.SetUpdateTime(*t)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *ArtworkCreate) SetDeletedAt(t time.Time) *ArtworkCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableDeletedAt(t *time.Time) *ArtworkCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetTitle sets the "title" field.
func (ac *ArtworkCreate) SetTitle(s string) *ArtworkCreate {
	ac.mutation.SetTitle(s)
	return ac
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableTitle(s *string) *ArtworkCreate {
	if s != nil {
		ac.SetTitle(*s)
	}
	return ac
}

// SetDescription sets the "description" field.
func (ac *ArtworkCreate) SetDescription(s string) *ArtworkCreate {
	ac.mutation.SetDescription(s)
	return ac
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableDescription(s *string) *ArtworkCreate {
	if s != nil {
		ac.SetDescription(*s)
	}
	return ac
}

// SetIsAi sets the "is_ai" field.
func (ac *ArtworkCreate) SetIsAi(b bool) *ArtworkCreate {
	ac.mutation.SetIsAi(b)
	return ac
}

// SetNillableIsAi sets the "is_ai" field if the given value is not nil.
func (ac *ArtworkCreate) SetNillableIsAi(b *bool) *ArtworkCreate {
	if b != nil {
		ac.SetIsAi(*b)
	}
	return ac
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (ac *ArtworkCreate) AddTagIDs(ids ...int) *ArtworkCreate {
	ac.mutation.AddTagIDs(ids...)
	return ac
}

// AddTags adds the "tags" edges to the Tag entity.
func (ac *ArtworkCreate) AddTags(t ...*Tag) *ArtworkCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTagIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (ac *ArtworkCreate) SetOwnerID(id int) *ArtworkCreate {
	ac.mutation.SetOwnerID(id)
	return ac
}

// SetOwner sets the "owner" edge to the User entity.
func (ac *ArtworkCreate) SetOwner(u *User) *ArtworkCreate {
	return ac.SetOwnerID(u.ID)
}

// AddLikeIDs adds the "likes" edge to the User entity by IDs.
func (ac *ArtworkCreate) AddLikeIDs(ids ...int) *ArtworkCreate {
	ac.mutation.AddLikeIDs(ids...)
	return ac
}

// AddLikes adds the "likes" edges to the User entity.
func (ac *ArtworkCreate) AddLikes(u ...*User) *ArtworkCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ac.AddLikeIDs(ids...)
}

// SetMediaID sets the "media" edge to the Media entity by ID.
func (ac *ArtworkCreate) SetMediaID(id int) *ArtworkCreate {
	ac.mutation.SetMediaID(id)
	return ac
}

// SetMedia sets the "media" edge to the Media entity.
func (ac *ArtworkCreate) SetMedia(m *Media) *ArtworkCreate {
	return ac.SetMediaID(m.ID)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (ac *ArtworkCreate) AddCommentIDs(ids ...int) *ArtworkCreate {
	ac.mutation.AddCommentIDs(ids...)
	return ac
}

// AddComments adds the "comments" edges to the Comment entity.
func (ac *ArtworkCreate) AddComments(c ...*Comment) *ArtworkCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ac.AddCommentIDs(ids...)
}

// SetCommentGenerateID sets the "comment_generate" edge to the Comment entity by ID.
func (ac *ArtworkCreate) SetCommentGenerateID(id int) *ArtworkCreate {
	ac.mutation.SetCommentGenerateID(id)
	return ac
}

// SetNillableCommentGenerateID sets the "comment_generate" edge to the Comment entity by ID if the given value is not nil.
func (ac *ArtworkCreate) SetNillableCommentGenerateID(id *int) *ArtworkCreate {
	if id != nil {
		ac = ac.SetCommentGenerateID(*id)
	}
	return ac
}

// SetCommentGenerate sets the "comment_generate" edge to the Comment entity.
func (ac *ArtworkCreate) SetCommentGenerate(c *Comment) *ArtworkCreate {
	return ac.SetCommentGenerateID(c.ID)
}

// Mutation returns the ArtworkMutation object of the builder.
func (ac *ArtworkCreate) Mutation() *ArtworkMutation {
	return ac.mutation
}

// Save creates the Artwork in the database.
func (ac *ArtworkCreate) Save(ctx context.Context) (*Artwork, error) {
	if err := ac.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ArtworkCreate) SaveX(ctx context.Context) *Artwork {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ArtworkCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ArtworkCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *ArtworkCreate) defaults() error {
	if _, ok := ac.mutation.CreateTime(); !ok {
		if artwork.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized artwork.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := artwork.DefaultCreateTime()
		ac.mutation.SetCreateTime(v)
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		if artwork.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized artwork.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := artwork.DefaultUpdateTime()
		ac.mutation.SetUpdateTime(v)
	}
	if _, ok := ac.mutation.IsAi(); !ok {
		v := artwork.DefaultIsAi
		ac.mutation.SetIsAi(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ac *ArtworkCreate) check() error {
	if _, ok := ac.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Artwork.create_time"`)}
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Artwork.update_time"`)}
	}
	if _, ok := ac.mutation.IsAi(); !ok {
		return &ValidationError{Name: "is_ai", err: errors.New(`ent: missing required field "Artwork.is_ai"`)}
	}
	if len(ac.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Artwork.owner"`)}
	}
	if len(ac.mutation.MediaIDs()) == 0 {
		return &ValidationError{Name: "media", err: errors.New(`ent: missing required edge "Artwork.media"`)}
	}
	return nil
}

func (ac *ArtworkCreate) sqlSave(ctx context.Context) (*Artwork, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ArtworkCreate) createSpec() (*Artwork, *sqlgraph.CreateSpec) {
	var (
		_node = &Artwork{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(artwork.Table, sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.CreateTime(); ok {
		_spec.SetField(artwork.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ac.mutation.UpdateTime(); ok {
		_spec.SetField(artwork.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.SetField(artwork.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := ac.mutation.Title(); ok {
		_spec.SetField(artwork.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ac.mutation.Description(); ok {
		_spec.SetField(artwork.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ac.mutation.IsAi(); ok {
		_spec.SetField(artwork.FieldIsAi, field.TypeBool, value)
		_node.IsAi = value
	}
	if nodes := ac.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   artwork.TagsTable,
			Columns: artwork.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artwork.OwnerTable,
			Columns: []string{artwork.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_artworks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   artwork.LikesTable,
			Columns: artwork.LikesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artwork.MediaTable,
			Columns: []string{artwork.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.media_artworks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   artwork.CommentsTable,
			Columns: artwork.CommentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.CommentGenerateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   artwork.CommentGenerateTable,
			Columns: []string{artwork.CommentGenerateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.comment_generated_artwork = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ArtworkCreateBulk is the builder for creating many Artwork entities in bulk.
type ArtworkCreateBulk struct {
	config
	err      error
	builders []*ArtworkCreate
}

// Save creates the Artwork entities in the database.
func (acb *ArtworkCreateBulk) Save(ctx context.Context) ([]*Artwork, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Artwork, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtworkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ArtworkCreateBulk) SaveX(ctx context.Context) []*Artwork {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ArtworkCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ArtworkCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
