// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/aspectratio"
)

// AspectRatioCreate is the builder for creating a AspectRatio entity.
type AspectRatioCreate struct {
	config
	mutation *AspectRatioMutation
	hooks    []Hook
}

// SetRatio sets the "ratio" field.
func (arc *AspectRatioCreate) SetRatio(s string) *AspectRatioCreate {
	arc.mutation.SetRatio(s)
	return arc
}

// SetWidth sets the "width" field.
func (arc *AspectRatioCreate) SetWidth(i int) *AspectRatioCreate {
	arc.mutation.SetWidth(i)
	return arc
}

// SetHeight sets the "height" field.
func (arc *AspectRatioCreate) SetHeight(i int) *AspectRatioCreate {
	arc.mutation.SetHeight(i)
	return arc
}

// Mutation returns the AspectRatioMutation object of the builder.
func (arc *AspectRatioCreate) Mutation() *AspectRatioMutation {
	return arc.mutation
}

// Save creates the AspectRatio in the database.
func (arc *AspectRatioCreate) Save(ctx context.Context) (*AspectRatio, error) {
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *AspectRatioCreate) SaveX(ctx context.Context) *AspectRatio {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *AspectRatioCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *AspectRatioCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (arc *AspectRatioCreate) check() error {
	if _, ok := arc.mutation.Ratio(); !ok {
		return &ValidationError{Name: "ratio", err: errors.New(`ent: missing required field "AspectRatio.ratio"`)}
	}
	if _, ok := arc.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "AspectRatio.width"`)}
	}
	if _, ok := arc.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "AspectRatio.height"`)}
	}
	return nil
}

func (arc *AspectRatioCreate) sqlSave(ctx context.Context) (*AspectRatio, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *AspectRatioCreate) createSpec() (*AspectRatio, *sqlgraph.CreateSpec) {
	var (
		_node = &AspectRatio{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(aspectratio.Table, sqlgraph.NewFieldSpec(aspectratio.FieldID, field.TypeInt))
	)
	if value, ok := arc.mutation.Ratio(); ok {
		_spec.SetField(aspectratio.FieldRatio, field.TypeString, value)
		_node.Ratio = value
	}
	if value, ok := arc.mutation.Width(); ok {
		_spec.SetField(aspectratio.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := arc.mutation.Height(); ok {
		_spec.SetField(aspectratio.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	return _node, _spec
}

// AspectRatioCreateBulk is the builder for creating many AspectRatio entities in bulk.
type AspectRatioCreateBulk struct {
	config
	err      error
	builders []*AspectRatioCreate
}

// Save creates the AspectRatio entities in the database.
func (arcb *AspectRatioCreateBulk) Save(ctx context.Context) ([]*AspectRatio, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*AspectRatio, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AspectRatioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *AspectRatioCreateBulk) SaveX(ctx context.Context) []*AspectRatio {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *AspectRatioCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *AspectRatioCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}
