// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/baseconfig"
	"github.com/MiaoMint/animaerd/ent/predicate"
)

// BaseConfigDelete is the builder for deleting a BaseConfig entity.
type BaseConfigDelete struct {
	config
	hooks    []Hook
	mutation *BaseConfigMutation
}

// Where appends a list predicates to the BaseConfigDelete builder.
func (bcd *BaseConfigDelete) Where(ps ...predicate.BaseConfig) *BaseConfigDelete {
	bcd.mutation.Where(ps...)
	return bcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bcd *BaseConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bcd.sqlExec, bcd.mutation, bcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bcd *BaseConfigDelete) ExecX(ctx context.Context) int {
	n, err := bcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bcd *BaseConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(baseconfig.Table, sqlgraph.NewFieldSpec(baseconfig.FieldID, field.TypeInt))
	if ps := bcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bcd.mutation.done = true
	return affected, err
}

// BaseConfigDeleteOne is the builder for deleting a single BaseConfig entity.
type BaseConfigDeleteOne struct {
	bcd *BaseConfigDelete
}

// Where appends a list predicates to the BaseConfigDelete builder.
func (bcdo *BaseConfigDeleteOne) Where(ps ...predicate.BaseConfig) *BaseConfigDeleteOne {
	bcdo.bcd.mutation.Where(ps...)
	return bcdo
}

// Exec executes the deletion query.
func (bcdo *BaseConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := bcdo.bcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{baseconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bcdo *BaseConfigDeleteOne) ExecX(ctx context.Context) {
	if err := bcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
