// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/comfyuinode"
	"github.com/MiaoMint/animaerd/ent/predicate"
)

// ComfyUINodeDelete is the builder for deleting a ComfyUINode entity.
type ComfyUINodeDelete struct {
	config
	hooks    []Hook
	mutation *ComfyUINodeMutation
}

// Where appends a list predicates to the ComfyUINodeDelete builder.
func (cund *ComfyUINodeDelete) Where(ps ...predicate.ComfyUINode) *ComfyUINodeDelete {
	cund.mutation.Where(ps...)
	return cund
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cund *ComfyUINodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cund.sqlExec, cund.mutation, cund.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cund *ComfyUINodeDelete) ExecX(ctx context.Context) int {
	n, err := cund.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cund *ComfyUINodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(comfyuinode.Table, sqlgraph.NewFieldSpec(comfyuinode.FieldID, field.TypeInt))
	if ps := cund.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cund.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cund.mutation.done = true
	return affected, err
}

// ComfyUINodeDeleteOne is the builder for deleting a single ComfyUINode entity.
type ComfyUINodeDeleteOne struct {
	cund *ComfyUINodeDelete
}

// Where appends a list predicates to the ComfyUINodeDelete builder.
func (cundo *ComfyUINodeDeleteOne) Where(ps ...predicate.ComfyUINode) *ComfyUINodeDeleteOne {
	cundo.cund.mutation.Where(ps...)
	return cundo
}

// Exec executes the deletion query.
func (cundo *ComfyUINodeDeleteOne) Exec(ctx context.Context) error {
	n, err := cundo.cund.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{comfyuinode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cundo *ComfyUINodeDeleteOne) ExecX(ctx context.Context) {
	if err := cundo.Exec(ctx); err != nil {
		panic(err)
	}
}
