// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/comfyuinode"
)

// ComfyUINodeCreate is the builder for creating a ComfyUINode entity.
type ComfyUINodeCreate struct {
	config
	mutation *ComfyUINodeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (cunc *ComfyUINodeCreate) SetCreateTime(t time.Time) *ComfyUINodeCreate {
	cunc.mutation.SetCreateTime(t)
	return cunc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (cunc *ComfyUINodeCreate) SetNillableCreateTime(t *time.Time) *ComfyUINodeCreate {
	if t != nil {
		cunc.SetCreateTime(*t)
	}
	return cunc
}

// SetUpdateTime sets the "update_time" field.
func (cunc *ComfyUINodeCreate) SetUpdateTime(t time.Time) *ComfyUINodeCreate {
	cunc.mutation.SetUpdateTime(t)
	return cunc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (cunc *ComfyUINodeCreate) SetNillableUpdateTime(t *time.Time) *ComfyUINodeCreate {
	if t != nil {
		cunc.SetUpdateTime(*t)
	}
	return cunc
}

// SetName sets the "name" field.
func (cunc *ComfyUINodeCreate) SetName(s string) *ComfyUINodeCreate {
	cunc.mutation.SetName(s)
	return cunc
}

// SetEndpoint sets the "endpoint" field.
func (cunc *ComfyUINodeCreate) SetEndpoint(s string) *ComfyUINodeCreate {
	cunc.mutation.SetEndpoint(s)
	return cunc
}

// SetEnabled sets the "enabled" field.
func (cunc *ComfyUINodeCreate) SetEnabled(b bool) *ComfyUINodeCreate {
	cunc.mutation.SetEnabled(b)
	return cunc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (cunc *ComfyUINodeCreate) SetNillableEnabled(b *bool) *ComfyUINodeCreate {
	if b != nil {
		cunc.SetEnabled(*b)
	}
	return cunc
}

// Mutation returns the ComfyUINodeMutation object of the builder.
func (cunc *ComfyUINodeCreate) Mutation() *ComfyUINodeMutation {
	return cunc.mutation
}

// Save creates the ComfyUINode in the database.
func (cunc *ComfyUINodeCreate) Save(ctx context.Context) (*ComfyUINode, error) {
	cunc.defaults()
	return withHooks(ctx, cunc.sqlSave, cunc.mutation, cunc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cunc *ComfyUINodeCreate) SaveX(ctx context.Context) *ComfyUINode {
	v, err := cunc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cunc *ComfyUINodeCreate) Exec(ctx context.Context) error {
	_, err := cunc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cunc *ComfyUINodeCreate) ExecX(ctx context.Context) {
	if err := cunc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cunc *ComfyUINodeCreate) defaults() {
	if _, ok := cunc.mutation.CreateTime(); !ok {
		v := comfyuinode.DefaultCreateTime()
		cunc.mutation.SetCreateTime(v)
	}
	if _, ok := cunc.mutation.UpdateTime(); !ok {
		v := comfyuinode.DefaultUpdateTime()
		cunc.mutation.SetUpdateTime(v)
	}
	if _, ok := cunc.mutation.Enabled(); !ok {
		v := comfyuinode.DefaultEnabled
		cunc.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cunc *ComfyUINodeCreate) check() error {
	if _, ok := cunc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ComfyUINode.create_time"`)}
	}
	if _, ok := cunc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ComfyUINode.update_time"`)}
	}
	if _, ok := cunc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ComfyUINode.name"`)}
	}
	if _, ok := cunc.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "ComfyUINode.endpoint"`)}
	}
	if _, ok := cunc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ComfyUINode.enabled"`)}
	}
	return nil
}

func (cunc *ComfyUINodeCreate) sqlSave(ctx context.Context) (*ComfyUINode, error) {
	if err := cunc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cunc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cunc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cunc.mutation.id = &_node.ID
	cunc.mutation.done = true
	return _node, nil
}

func (cunc *ComfyUINodeCreate) createSpec() (*ComfyUINode, *sqlgraph.CreateSpec) {
	var (
		_node = &ComfyUINode{config: cunc.config}
		_spec = sqlgraph.NewCreateSpec(comfyuinode.Table, sqlgraph.NewFieldSpec(comfyuinode.FieldID, field.TypeInt))
	)
	if value, ok := cunc.mutation.CreateTime(); ok {
		_spec.SetField(comfyuinode.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := cunc.mutation.UpdateTime(); ok {
		_spec.SetField(comfyuinode.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := cunc.mutation.Name(); ok {
		_spec.SetField(comfyuinode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cunc.mutation.Endpoint(); ok {
		_spec.SetField(comfyuinode.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := cunc.mutation.Enabled(); ok {
		_spec.SetField(comfyuinode.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// ComfyUINodeCreateBulk is the builder for creating many ComfyUINode entities in bulk.
type ComfyUINodeCreateBulk struct {
	config
	err      error
	builders []*ComfyUINodeCreate
}

// Save creates the ComfyUINode entities in the database.
func (cuncb *ComfyUINodeCreateBulk) Save(ctx context.Context) ([]*ComfyUINode, error) {
	if cuncb.err != nil {
		return nil, cuncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cuncb.builders))
	nodes := make([]*ComfyUINode, len(cuncb.builders))
	mutators := make([]Mutator, len(cuncb.builders))
	for i := range cuncb.builders {
		func(i int, root context.Context) {
			builder := cuncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComfyUINodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cuncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cuncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cuncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cuncb *ComfyUINodeCreateBulk) SaveX(ctx context.Context) []*ComfyUINode {
	v, err := cuncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cuncb *ComfyUINodeCreateBulk) Exec(ctx context.Context) error {
	_, err := cuncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuncb *ComfyUINodeCreateBulk) ExecX(ctx context.Context) {
	if err := cuncb.Exec(ctx); err != nil {
		panic(err)
	}
}
