// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/artwork"
	"github.com/MiaoMint/animaerd/ent/media"
	"github.com/MiaoMint/animaerd/ent/predicate"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks    []Hook
	mutation *MediaMutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (mu *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetURL sets the "url" field.
func (mu *MediaUpdate) SetURL(s string) *MediaUpdate {
	mu.mutation.SetURL(s)
	return mu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableURL(s *string) *MediaUpdate {
	if s != nil {
		mu.SetURL(*s)
	}
	return mu
}

// SetKey sets the "key" field.
func (mu *MediaUpdate) SetKey(s string) *MediaUpdate {
	mu.mutation.SetKey(s)
	return mu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableKey(s *string) *MediaUpdate {
	if s != nil {
		mu.SetKey(*s)
	}
	return mu
}

// SetSize sets the "size" field.
func (mu *MediaUpdate) SetSize(i int) *MediaUpdate {
	mu.mutation.ResetSize()
	mu.mutation.SetSize(i)
	return mu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableSize(i *int) *MediaUpdate {
	if i != nil {
		mu.SetSize(*i)
	}
	return mu
}

// AddSize adds i to the "size" field.
func (mu *MediaUpdate) AddSize(i int) *MediaUpdate {
	mu.mutation.AddSize(i)
	return mu
}

// SetWidth sets the "width" field.
func (mu *MediaUpdate) SetWidth(i int) *MediaUpdate {
	mu.mutation.ResetWidth()
	mu.mutation.SetWidth(i)
	return mu
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableWidth(i *int) *MediaUpdate {
	if i != nil {
		mu.SetWidth(*i)
	}
	return mu
}

// AddWidth adds i to the "width" field.
func (mu *MediaUpdate) AddWidth(i int) *MediaUpdate {
	mu.mutation.AddWidth(i)
	return mu
}

// SetHeight sets the "height" field.
func (mu *MediaUpdate) SetHeight(i int) *MediaUpdate {
	mu.mutation.ResetHeight()
	mu.mutation.SetHeight(i)
	return mu
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableHeight(i *int) *MediaUpdate {
	if i != nil {
		mu.SetHeight(*i)
	}
	return mu
}

// AddHeight adds i to the "height" field.
func (mu *MediaUpdate) AddHeight(i int) *MediaUpdate {
	mu.mutation.AddHeight(i)
	return mu
}

// SetPrimaryCorlor sets the "primary_corlor" field.
func (mu *MediaUpdate) SetPrimaryCorlor(s string) *MediaUpdate {
	mu.mutation.SetPrimaryCorlor(s)
	return mu
}

// SetNillablePrimaryCorlor sets the "primary_corlor" field if the given value is not nil.
func (mu *MediaUpdate) SetNillablePrimaryCorlor(s *string) *MediaUpdate {
	if s != nil {
		mu.SetPrimaryCorlor(*s)
	}
	return mu
}

// SetHash sets the "hash" field.
func (mu *MediaUpdate) SetHash(s string) *MediaUpdate {
	mu.mutation.SetHash(s)
	return mu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableHash(s *string) *MediaUpdate {
	if s != nil {
		mu.SetHash(*s)
	}
	return mu
}

// AddArtworkIDs adds the "artworks" edge to the Artwork entity by IDs.
func (mu *MediaUpdate) AddArtworkIDs(ids ...int) *MediaUpdate {
	mu.mutation.AddArtworkIDs(ids...)
	return mu
}

// AddArtworks adds the "artworks" edges to the Artwork entity.
func (mu *MediaUpdate) AddArtworks(a ...*Artwork) *MediaUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mu.AddArtworkIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (mu *MediaUpdate) Mutation() *MediaMutation {
	return mu.mutation
}

// ClearArtworks clears all "artworks" edges to the Artwork entity.
func (mu *MediaUpdate) ClearArtworks() *MediaUpdate {
	mu.mutation.ClearArtworks()
	return mu
}

// RemoveArtworkIDs removes the "artworks" edge to Artwork entities by IDs.
func (mu *MediaUpdate) RemoveArtworkIDs(ids ...int) *MediaUpdate {
	mu.mutation.RemoveArtworkIDs(ids...)
	return mu
}

// RemoveArtworks removes "artworks" edges to Artwork entities.
func (mu *MediaUpdate) RemoveArtworks(a ...*Artwork) *MediaUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mu.RemoveArtworkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MediaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MediaUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MediaUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MediaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := mu.mutation.Key(); ok {
		_spec.SetField(media.FieldKey, field.TypeString, value)
	}
	if value, ok := mu.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeInt, value)
	}
	if value, ok := mu.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := mu.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := mu.mutation.PrimaryCorlor(); ok {
		_spec.SetField(media.FieldPrimaryCorlor, field.TypeString, value)
	}
	if value, ok := mu.mutation.Hash(); ok {
		_spec.SetField(media.FieldHash, field.TypeString, value)
	}
	if mu.mutation.ArtworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedArtworksIDs(); len(nodes) > 0 && !mu.mutation.ArtworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ArtworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaMutation
}

// SetURL sets the "url" field.
func (muo *MediaUpdateOne) SetURL(s string) *MediaUpdateOne {
	muo.mutation.SetURL(s)
	return muo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableURL(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetURL(*s)
	}
	return muo
}

// SetKey sets the "key" field.
func (muo *MediaUpdateOne) SetKey(s string) *MediaUpdateOne {
	muo.mutation.SetKey(s)
	return muo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableKey(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetKey(*s)
	}
	return muo
}

// SetSize sets the "size" field.
func (muo *MediaUpdateOne) SetSize(i int) *MediaUpdateOne {
	muo.mutation.ResetSize()
	muo.mutation.SetSize(i)
	return muo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableSize(i *int) *MediaUpdateOne {
	if i != nil {
		muo.SetSize(*i)
	}
	return muo
}

// AddSize adds i to the "size" field.
func (muo *MediaUpdateOne) AddSize(i int) *MediaUpdateOne {
	muo.mutation.AddSize(i)
	return muo
}

// SetWidth sets the "width" field.
func (muo *MediaUpdateOne) SetWidth(i int) *MediaUpdateOne {
	muo.mutation.ResetWidth()
	muo.mutation.SetWidth(i)
	return muo
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableWidth(i *int) *MediaUpdateOne {
	if i != nil {
		muo.SetWidth(*i)
	}
	return muo
}

// AddWidth adds i to the "width" field.
func (muo *MediaUpdateOne) AddWidth(i int) *MediaUpdateOne {
	muo.mutation.AddWidth(i)
	return muo
}

// SetHeight sets the "height" field.
func (muo *MediaUpdateOne) SetHeight(i int) *MediaUpdateOne {
	muo.mutation.ResetHeight()
	muo.mutation.SetHeight(i)
	return muo
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableHeight(i *int) *MediaUpdateOne {
	if i != nil {
		muo.SetHeight(*i)
	}
	return muo
}

// AddHeight adds i to the "height" field.
func (muo *MediaUpdateOne) AddHeight(i int) *MediaUpdateOne {
	muo.mutation.AddHeight(i)
	return muo
}

// SetPrimaryCorlor sets the "primary_corlor" field.
func (muo *MediaUpdateOne) SetPrimaryCorlor(s string) *MediaUpdateOne {
	muo.mutation.SetPrimaryCorlor(s)
	return muo
}

// SetNillablePrimaryCorlor sets the "primary_corlor" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillablePrimaryCorlor(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetPrimaryCorlor(*s)
	}
	return muo
}

// SetHash sets the "hash" field.
func (muo *MediaUpdateOne) SetHash(s string) *MediaUpdateOne {
	muo.mutation.SetHash(s)
	return muo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableHash(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetHash(*s)
	}
	return muo
}

// AddArtworkIDs adds the "artworks" edge to the Artwork entity by IDs.
func (muo *MediaUpdateOne) AddArtworkIDs(ids ...int) *MediaUpdateOne {
	muo.mutation.AddArtworkIDs(ids...)
	return muo
}

// AddArtworks adds the "artworks" edges to the Artwork entity.
func (muo *MediaUpdateOne) AddArtworks(a ...*Artwork) *MediaUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return muo.AddArtworkIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (muo *MediaUpdateOne) Mutation() *MediaMutation {
	return muo.mutation
}

// ClearArtworks clears all "artworks" edges to the Artwork entity.
func (muo *MediaUpdateOne) ClearArtworks() *MediaUpdateOne {
	muo.mutation.ClearArtworks()
	return muo
}

// RemoveArtworkIDs removes the "artworks" edge to Artwork entities by IDs.
func (muo *MediaUpdateOne) RemoveArtworkIDs(ids ...int) *MediaUpdateOne {
	muo.mutation.RemoveArtworkIDs(ids...)
	return muo
}

// RemoveArtworks removes "artworks" edges to Artwork entities.
func (muo *MediaUpdateOne) RemoveArtworks(a ...*Artwork) *MediaUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return muo.RemoveArtworkIDs(ids...)
}

// Where appends a list predicates to the MediaUpdate builder.
func (muo *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Media entity.
func (muo *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := muo.mutation.Key(); ok {
		_spec.SetField(media.FieldKey, field.TypeString, value)
	}
	if value, ok := muo.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeInt, value)
	}
	if value, ok := muo.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt, value)
	}
	if value, ok := muo.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt, value)
	}
	if value, ok := muo.mutation.PrimaryCorlor(); ok {
		_spec.SetField(media.FieldPrimaryCorlor, field.TypeString, value)
	}
	if value, ok := muo.mutation.Hash(); ok {
		_spec.SetField(media.FieldHash, field.TypeString, value)
	}
	if muo.mutation.ArtworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedArtworksIDs(); len(nodes) > 0 && !muo.mutation.ArtworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ArtworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   media.ArtworksTable,
			Columns: []string{media.ArtworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artwork.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Media{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
