// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/style"
	"github.com/MiaoMint/animaerd/ent/workflow"
)

// StyleCreate is the builder for creating a Style entity.
type StyleCreate struct {
	config
	mutation *StyleMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sc *StyleCreate) SetCreateTime(t time.Time) *StyleCreate {
	sc.mutation.SetCreateTime(t)
	return sc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sc *StyleCreate) SetNillableCreateTime(t *time.Time) *StyleCreate {
	if t != nil {
		sc.SetCreateTime(*t)
	}
	return sc
}

// SetUpdateTime sets the "update_time" field.
func (sc *StyleCreate) SetUpdateTime(t time.Time) *StyleCreate {
	sc.mutation.SetUpdateTime(t)
	return sc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sc *StyleCreate) SetNillableUpdateTime(t *time.Time) *StyleCreate {
	if t != nil {
		sc.SetUpdateTime(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *StyleCreate) SetDeletedAt(t time.Time) *StyleCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *StyleCreate) SetNillableDeletedAt(t *time.Time) *StyleCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetName sets the "name" field.
func (sc *StyleCreate) SetName(s string) *StyleCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetIcon sets the "icon" field.
func (sc *StyleCreate) SetIcon(s string) *StyleCreate {
	sc.mutation.SetIcon(s)
	return sc
}

// SetWorkflowsID sets the "workflows" edge to the Workflow entity by ID.
func (sc *StyleCreate) SetWorkflowsID(id int) *StyleCreate {
	sc.mutation.SetWorkflowsID(id)
	return sc
}

// SetNillableWorkflowsID sets the "workflows" edge to the Workflow entity by ID if the given value is not nil.
func (sc *StyleCreate) SetNillableWorkflowsID(id *int) *StyleCreate {
	if id != nil {
		sc = sc.SetWorkflowsID(*id)
	}
	return sc
}

// SetWorkflows sets the "workflows" edge to the Workflow entity.
func (sc *StyleCreate) SetWorkflows(w *Workflow) *StyleCreate {
	return sc.SetWorkflowsID(w.ID)
}

// Mutation returns the StyleMutation object of the builder.
func (sc *StyleCreate) Mutation() *StyleMutation {
	return sc.mutation
}

// Save creates the Style in the database.
func (sc *StyleCreate) Save(ctx context.Context) (*Style, error) {
	if err := sc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StyleCreate) SaveX(ctx context.Context) *Style {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StyleCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StyleCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StyleCreate) defaults() error {
	if _, ok := sc.mutation.CreateTime(); !ok {
		if style.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized style.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := style.DefaultCreateTime()
		sc.mutation.SetCreateTime(v)
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		if style.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized style.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := style.DefaultUpdateTime()
		sc.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sc *StyleCreate) check() error {
	if _, ok := sc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Style.create_time"`)}
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Style.update_time"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Style.name"`)}
	}
	if _, ok := sc.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Style.icon"`)}
	}
	return nil
}

func (sc *StyleCreate) sqlSave(ctx context.Context) (*Style, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StyleCreate) createSpec() (*Style, *sqlgraph.CreateSpec) {
	var (
		_node = &Style{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(style.Table, sqlgraph.NewFieldSpec(style.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.CreateTime(); ok {
		_spec.SetField(style.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := sc.mutation.UpdateTime(); ok {
		_spec.SetField(style.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(style.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(style.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Icon(); ok {
		_spec.SetField(style.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if nodes := sc.mutation.WorkflowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   style.WorkflowsTable,
			Columns: []string{style.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StyleCreateBulk is the builder for creating many Style entities in bulk.
type StyleCreateBulk struct {
	config
	err      error
	builders []*StyleCreate
}

// Save creates the Style entities in the database.
func (scb *StyleCreateBulk) Save(ctx context.Context) ([]*Style, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Style, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StyleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StyleCreateBulk) SaveX(ctx context.Context) []*Style {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StyleCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StyleCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
