// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MiaoMint/animaerd/ent/predicate"
	"github.com/MiaoMint/animaerd/ent/style"
	"github.com/MiaoMint/animaerd/ent/workflow"
)

// StyleUpdate is the builder for updating Style entities.
type StyleUpdate struct {
	config
	hooks    []Hook
	mutation *StyleMutation
}

// Where appends a list predicates to the StyleUpdate builder.
func (su *StyleUpdate) Where(ps ...predicate.Style) *StyleUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *StyleUpdate) SetUpdateTime(t time.Time) *StyleUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *StyleUpdate) SetDeletedAt(t time.Time) *StyleUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *StyleUpdate) SetNillableDeletedAt(t *time.Time) *StyleUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *StyleUpdate) ClearDeletedAt() *StyleUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetName sets the "name" field.
func (su *StyleUpdate) SetName(s string) *StyleUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *StyleUpdate) SetNillableName(s *string) *StyleUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetIcon sets the "icon" field.
func (su *StyleUpdate) SetIcon(s string) *StyleUpdate {
	su.mutation.SetIcon(s)
	return su
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (su *StyleUpdate) SetNillableIcon(s *string) *StyleUpdate {
	if s != nil {
		su.SetIcon(*s)
	}
	return su
}

// SetWorkflowsID sets the "workflows" edge to the Workflow entity by ID.
func (su *StyleUpdate) SetWorkflowsID(id int) *StyleUpdate {
	su.mutation.SetWorkflowsID(id)
	return su
}

// SetNillableWorkflowsID sets the "workflows" edge to the Workflow entity by ID if the given value is not nil.
func (su *StyleUpdate) SetNillableWorkflowsID(id *int) *StyleUpdate {
	if id != nil {
		su = su.SetWorkflowsID(*id)
	}
	return su
}

// SetWorkflows sets the "workflows" edge to the Workflow entity.
func (su *StyleUpdate) SetWorkflows(w *Workflow) *StyleUpdate {
	return su.SetWorkflowsID(w.ID)
}

// Mutation returns the StyleMutation object of the builder.
func (su *StyleUpdate) Mutation() *StyleMutation {
	return su.mutation
}

// ClearWorkflows clears the "workflows" edge to the Workflow entity.
func (su *StyleUpdate) ClearWorkflows() *StyleUpdate {
	su.mutation.ClearWorkflows()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StyleUpdate) Save(ctx context.Context) (int, error) {
	if err := su.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StyleUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StyleUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StyleUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *StyleUpdate) defaults() error {
	if _, ok := su.mutation.UpdateTime(); !ok {
		if style.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized style.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := style.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
	return nil
}

func (su *StyleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(style.Table, style.Columns, sqlgraph.NewFieldSpec(style.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(style.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(style.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(style.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(style.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Icon(); ok {
		_spec.SetField(style.FieldIcon, field.TypeString, value)
	}
	if su.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   style.WorkflowsTable,
			Columns: []string{style.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.WorkflowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   style.WorkflowsTable,
			Columns: []string{style.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{style.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StyleUpdateOne is the builder for updating a single Style entity.
type StyleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StyleMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *StyleUpdateOne) SetUpdateTime(t time.Time) *StyleUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *StyleUpdateOne) SetDeletedAt(t time.Time) *StyleUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *StyleUpdateOne) SetNillableDeletedAt(t *time.Time) *StyleUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *StyleUpdateOne) ClearDeletedAt() *StyleUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetName sets the "name" field.
func (suo *StyleUpdateOne) SetName(s string) *StyleUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *StyleUpdateOne) SetNillableName(s *string) *StyleUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetIcon sets the "icon" field.
func (suo *StyleUpdateOne) SetIcon(s string) *StyleUpdateOne {
	suo.mutation.SetIcon(s)
	return suo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (suo *StyleUpdateOne) SetNillableIcon(s *string) *StyleUpdateOne {
	if s != nil {
		suo.SetIcon(*s)
	}
	return suo
}

// SetWorkflowsID sets the "workflows" edge to the Workflow entity by ID.
func (suo *StyleUpdateOne) SetWorkflowsID(id int) *StyleUpdateOne {
	suo.mutation.SetWorkflowsID(id)
	return suo
}

// SetNillableWorkflowsID sets the "workflows" edge to the Workflow entity by ID if the given value is not nil.
func (suo *StyleUpdateOne) SetNillableWorkflowsID(id *int) *StyleUpdateOne {
	if id != nil {
		suo = suo.SetWorkflowsID(*id)
	}
	return suo
}

// SetWorkflows sets the "workflows" edge to the Workflow entity.
func (suo *StyleUpdateOne) SetWorkflows(w *Workflow) *StyleUpdateOne {
	return suo.SetWorkflowsID(w.ID)
}

// Mutation returns the StyleMutation object of the builder.
func (suo *StyleUpdateOne) Mutation() *StyleMutation {
	return suo.mutation
}

// ClearWorkflows clears the "workflows" edge to the Workflow entity.
func (suo *StyleUpdateOne) ClearWorkflows() *StyleUpdateOne {
	suo.mutation.ClearWorkflows()
	return suo
}

// Where appends a list predicates to the StyleUpdate builder.
func (suo *StyleUpdateOne) Where(ps ...predicate.Style) *StyleUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StyleUpdateOne) Select(field string, fields ...string) *StyleUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Style entity.
func (suo *StyleUpdateOne) Save(ctx context.Context) (*Style, error) {
	if err := suo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StyleUpdateOne) SaveX(ctx context.Context) *Style {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StyleUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StyleUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *StyleUpdateOne) defaults() error {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		if style.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized style.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := style.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
	return nil
}

func (suo *StyleUpdateOne) sqlSave(ctx context.Context) (_node *Style, err error) {
	_spec := sqlgraph.NewUpdateSpec(style.Table, style.Columns, sqlgraph.NewFieldSpec(style.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Style.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, style.FieldID)
		for _, f := range fields {
			if !style.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != style.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(style.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(style.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(style.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(style.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Icon(); ok {
		_spec.SetField(style.FieldIcon, field.TypeString, value)
	}
	if suo.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   style.WorkflowsTable,
			Columns: []string{style.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.WorkflowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   style.WorkflowsTable,
			Columns: []string{style.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Style{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{style.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
